[package]
name = "typhon"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]
build = "bin/build.rs"

[[bin]]
doc = false
name = "tci"
path = "bin/interpreter.rs"

[build-dependencies]
lalrpop = "0.14.0"

[dependencies]
linefeed = "0.4"
