#!/usr/bin/python
# https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form

Grammar = Rule

Newline = NEWLINE

Rule = Rule_
Rule_ = Rule_ + Rule__, Rule__
Rule__ = LHS + ":" + RHS + Newline

LHS = IDENT
RHS = IDENT, STRING, \
    "[" + RHS + "]", \
    "{" + RHS + "}", \
    "(" + RHS + ")", \
    RHS + "|" + RHS, \
    RHS + "," + RHS
