#!/usr/bin/python
# i put this here so my text editor reads it as python

# syntax:
#  a = b is basic production
#  a = b + c is concatenation
#  a = b, c is alternation
#  a = {b} is optional
#  a = [b] is the same as EMPTY, {b}

Start = Program

Program = Stmt

Stmt = SimpleStmt, CompoundStmt
CompoundStmt = FuncDef
SimpleStmt = SmallStmt
SmallStmt = "hello"

Expression = "hello"
Arguments = Expression
FuncDef = "def" + IDENT + "(" + ")" + ":" + Suite
FuncCall = IDENT + "(" + (Arguments) + ")"

Suite = SimpleStmt, NEWLINE + INDENT + Stmt + DEDENT
